# Build settings
markdown:         kramdown
highlighter:      rouge
permalink:        pretty
paginate:         5 # jekyll-paginate plugin is enabled by default
plugins: # https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/about-github-pages-and-jekyll#plugins
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-redirect-from

# Social handles
social:
  twitter: jacobemcken
  disqus_short_name: jacobemcken

# Setup
title:            Jacob Emcken
tagline:          'There is no silver bullet'
description:      "A programmer's blog sharing personal insights on problem-solving, software development, and programming philosophies, with a focus on Clojure."
url:              https://www.emcken.dk
baseurl:          /

# Google Analytics
google_analytics_tracking_id: G-9QC9JZ037D

author:
  name:           'Jacob Emcken'
  url:            https://www.emcken.dk

# https://github.com/jekyll/jekyll-feed
feed:
  tags: true

relative_links:
  enabled:     true
  collections: true

incremental: true
livereload: true
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .clj-kondo/
  - .calva/
  - optimize_img.clj
  - assets/img/orig/
  - public/css/hyde.css
  - public/css/poole.css
  - public/css/tailwind.css
