# Build settings
markdown:         kramdown
highlighter:      rouge
permalink:        pretty
paginate:         5 # jekyll-paginate plugin is enabled by default
plugins: # https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/about-github-pages-and-jekyll#plugins
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Social handles
social:
  twitter: jacobemcken
  disqus_short_name: jacobemcken

# Setup
title:            Jacob Emcken
tagline:          'There is no silver bullet'
description:      "Blogging about a software developer's findings"
url:              https://www.emcken.dk
baseurl:          /

# Google Analytics
google_analytics_tracking_id: G-9QC9JZ037D

author:
  name:           'Jacob Emcken'
  url:            https://twitter.com/jacobemcken

# https://github.com/jekyll/jekyll-feed
feed:
  tags: true
